# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono NL"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 12.0
modify_font baseline         1
modify_font cell_height      90%
modify_font cell_width       90%
symbol_map                   U+E000-U+F8FF,U+F0000-U+FFFFF,U+100000-U+10ffff JetBrainsMonoNL Nerd Font

include Tokyo Night Moon.conf

font_features                none
font_size 12.0
modify_font baseline         2
modify_font cell_height      82%
modify_font cell_width       95%

active_tab_font_style        none
cursor_blink_interval        0
cursor_shape                 beam
cursor_trail                 1
cursor_trail_decay           0.1 0.3
cursor_trail_start_threshold 2
macos_colorspace             displayp3
macos_option_as_alt          yes
macos_titlebar_color         background
macos_thicken_font           0
window_padding_width         2
remember_window_size         no
initial_window_width         120c
initial_window_height        32c

# Rendering
sync_to_monitor              true

# Use alt text rendering (thicker strokes)
# text_composition_strategy    1.5 30
# Enable shadowless window
# dynamic_background_opacity   yes

# Custom tab bar
include statusbar.conf

# tab management
map cmd+t              new_tab_with_cwd !neighbor
map cmd+w              close_tab
map cmd+]              next_tab
map cmd+[              previous_tab
map cmd+1              goto_tab 1
map cmd+2              goto_tab 2
map cmd+3              goto_tab 3
map cmd+4              goto_tab 4
map cmd+5              goto_tab 5
map cmd+6              goto_tab 6
map cmd+7              goto_tab 7
map cmd+8              goto_tab 8
map cmd+9              goto_tab 9
map cmd+enter          new_window

# jump to beginning and end of word/line
map opt+left           send_text all \x1b\x62
map opt+right          send_text all \x1b\x66
map cmd+left           send_text all \x01
map cmd+right          send_text all \x05
map cmd+backspace      send_text all \x15

# other fn keys
map cmd+f              launch --type=overlay --stdin-source=@screen_scrollback /opt/homebrew/bin/fzf --no-sort --no-mouse --exact -i --tac
